var fs = require('fs')
, options = {
  key: fs.readFileSync('certificates/private_without_passphrase.key')
  , cert: fs.readFileSync('certificates/certificate.crt')
  , ca: fs.readFileSync('certificates/intermediate.crt')
}
, http = require('http')
, https = require('https')
, express = require('express')
, redis = require('redis').createClient()
, auth = require('./auth')
, sessions = require('./sessions')
, signup = require('./signup')
, paid = require('./paid')
, feeds = require('./feeds.js')
, folders = require('./folders.js')
, articles = require('./articles.js')
, labels = require('./labels.js')
, app = express()
  .use(express.static('static'))
  .use(express.json())
  .use(express.urlencoded())
app.all('*', function(req,res,next) {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "X-Requested-With")
  next()
})
app.post('/:user/tokens/json',sessions.post)
app.delete('/:user/tokens/json',auth,sessions.delete)
app.get('/:user/folders/json',folders.get)
app.get('/:user/folders/:folder/json',folders.folder.get)
app.post('/:user/folders/:folder/json',auth,folders.folder.post)
app.delete('/:user/folders/:folder/json',auth,folders.folder.delete)
app.get('/:user/labels/json',labels.get)
app.get('/:user/labels/:label/json',labels.label.get)
app.post('/:user/labels/:label/json',auth,labels.label.post)
app.get('/:user/feeds/json',feeds.get)
app.post('/:user/feeds/json',auth,feeds.post)
app.get('/feeds/*/json',feeds.feed.get)
app.post('/articles/json',articles.post)
app.get('/articles/:hash/json',articles.get)
app.post('/signup',signup.post)
app.post('/paid/:token',paid.post)
app.get('/:user/labels/:label*',function(req,res){res.sendfile('label.html')})
app.get('/:user/folders/:folder*',function(req,res){res.sendfile('label.html')})
app.get('/:user/feeds*',function(req,res){res.sendfile('label.html')})
app.get('/feeds/*',function(req,res){res.sendfile('label.html')})
app.get('/:user',function(req,res){res.sendfile('user.html')})
https.createServer(options,app).listen(8000)
http.createServer(express().use(function(req,res){res.redirect('https://feedreader.co'+req.url)})).listen(8080)
